name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      BASE_URL: '/ThinkFlow/'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.1'
          cache: 'npm'

      - name: Cache node modules
        uses: actions/cache@v3
        id: cache-npm
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Clean Install Dependencies
        run: |
          npm ci
          npm install -D terser
          echo "Checking installed versions:"
          npm ls vue @vitejs/plugin-vue vite terser

      - name: Create Build Environment
        run: |
          echo "Creating .env file"
          echo "VITE_BASE_URL=$BASE_URL" > .env
          echo "VITE_APP_VERSION=$(git rev-parse --short HEAD)" >> .env

      - name: Build
        run: |
          echo "Starting production build..."
          npm run build || (echo "Build failed" && exit 1)
          echo "Build completed successfully"
        env:
          NODE_ENV: production
          VITE_BASE_URL: ${{ env.BASE_URL }}

      - name: Verify Build Output
        run: |
          if [ ! -d "dist" ]; then
            echo "dist directory not found"
            exit 1
          fi
          
          echo "Checking critical files..."
          ls -la dist/
          
          if [ ! -f "dist/index.html" ]; then
            echo "index.html not found in dist"
            exit 1
          fi
          
          echo "Verifying index.html content..."
          if ! grep -q "\"$BASE_URL\"" dist/index.html && ! grep -q "\"$BASE_URL" dist/index.html; then
            echo "Warning: Base URL not found in index.html"
            echo "Content of index.html:"
            cat dist/index.html
          fi
          
          echo "Checking for JavaScript files..."
          js_files=$(find dist -name "*.js" -type f)
          if [ -z "$js_files" ]; then
            echo "No JavaScript files found in dist"
            exit 1
          fi
          
          echo "Checking JavaScript files..."
          for file in $js_files; do
            echo "Checking $file..."
            filesize=$(stat -f%z "$file" 2>/dev/null || stat -c%s "$file")
            if [ "$filesize" -lt 100 ]; then
              echo "Warning: $file seems too small ($filesize bytes)"
            fi
          done
          
          echo "Checking file sizes..."
          du -h dist/assets/js/*

      - name: Prepare Deployment
        run: |
          touch dist/.nojekyll
          cp dist/index.html dist/404.html
          
          echo "Verifying deployment files..."
          if [ ! -f "dist/.nojekyll" ]; then
            echo ".nojekyll file missing"
            exit 1
          fi
          
          if [ ! -f "dist/404.html" ]; then
            echo "404.html file missing"
            exit 1
          fi
          
          echo "Files ready for deployment:"
          tree dist || ls -R dist

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
          clean: true
          commit-message: "Deploy: ${{ github.sha }}" 